

KRD={
    1:'BAACAgIAAxkBAAEOfvxiJLqDCnKOI25Av2GcweBAoliyrgACXRYAAtZKKUkAATpjYv3HwMkjBA'
}
Pharh={
    1:"BAACAgIAAxkBAAEOleJiKNJXVE_NEes-yBZp8wjxFfsg9QACjhMAAsrQ0EqrabbcxRjlyyME",
    2:"BAACAgIAAxkBAAEOleRiKNJ2GTtnSSZFwU6LS7cR4tYrcQACvxkAAv3UGEuWOv1T04zgbiME",
    3:"BAACAgIAAxkBAAEOleZiKNKESvmQ7jmp75cMJPC6nRqS2wACdxAAAkN5aEu33rVj2hRuOiME"
}
Zugumomo={
    1:"BAACAgIAAxkBAAEOlehiKNLStQfJzzUcOXqqJp9S_EkFYgACNgIAAlruWUiv_u-eQV5zPiME",
    2:"BAACAgIAAxkBAAEOleliKNLS5zVqM5GOiNyC4l1ZUk6uZwACMwIAAvZEUEhz97gWI76P2yME",
    3:"BAACAgIAAxkBAAEOlepiKNLSSbOpqLLfGTUBlxMKvLfgYQACNwIAAlruWUiJ3Sp3PN8NiyME",
    4:"BAACAgIAAxkBAAEOletiKNLSf8pj0UxOqW_HEYDVdITk-gACNAIAAvZEUEj0JnA3hBB-ZSME",
    5:"BAACAgIAAxkBAAEOlexiKNLSXg-sV9E6Hvuvaaq0R203vwACOAIAAlruWUjIpiTxHqBVCiME",
    6:"BAACAgIAAxkBAAEOle1iKNLSTyyWrz62_SI16VC8WH7cAAM5AgACWu5ZSL4YQaSauU2MIwQ",
    7:"AAMCAgADGQEAAQ6V7mIo0tKmNzvGZKEOPrLpkXeHjkxUAAI6AgACWu5ZSMY6uAIf4THbAQAHcwADIwQ",
    8:"BAACAgIAAxkBAAEOle9iKNLSIEY2Eb23zOA1SKlt2GucKQACOwIAAlruWUi5JYCbVP4akCME",
    9:"BAACAgIAAxkBAAEOlfBiKNLSCXRBEoP4rTvoip26wULdzwACPAIAAlruWUgRsByJ8Uw4xCME",
    10: "BAACAgIAAxkBAAEOlfFiKNLSi0GW7l1NnJIneNzUYTbmuQACPQIAAlruWUgnCk-mSP7mGCME",
    11:"BAACAgIAAxkBAAEOlghiKNOUHYgl1NgPTOyilpntl_k6_QACPwIAAlruWUhoUgABpHUPiv8jBA",
    12:"BAACAgIAAxkBAAEOlgliKNOUm8Ow-x-SV5HC-RjYPTPz6wACOgIAAvZEUEhcEg_haJpA6iME",

}

Maindict={
    1:KRD,
    2:Pharh,
    3:Zugumomo,
}
